WIP: build android-ril / libril
  * Why the atomic.h patch does not apply in libcutils?

  * TODO switch from Google Git to Github because of checksums

  * Sort out errors left:

ril.cpp:4134:26: error: invalid type argument of unary '*' (have 'int')
ril.cpp:4135:32: error: invalid type argument of unary '*' (have 'int')
ril.cpp:4138:28: error: 'int RilSocket::commandFd' is protected within this context
ril.cpp:4139:34: error: 'int RilSocket::listenFd' is protected within this context